### ISSUE TITLE
Images beyond the first 100 images not capable of being viewed directly

### ISSUE THREAD

**Issue by Krando** [jrie/googlePanicImage#1]
This is a glorious addon and works wonderfully. It is also neater than perhaps any other addon that I have come across which seeks to offer the same utility.

It however appears to have one great error: though it works charmingly for the first 100 images and the "View" button appears on them, beyond the first 100, the addon becomes useless. 

I understand that this is due certain encodings that Google has applied but even if we click on the image, we don't get the "View" button anywhere.

Here's what it looks if you open up a picture beyond the first 100:

https://i.imgur.com/6xlM3L5.png

It is not possible to load up the image in a direct link.

I would be very glad if this could be fixed as this addon is steadily becoming popular.

**Comment by jrie** [comment]
Thank you for your feedback, it is much appreciated!

In order to follow up - could you provide me with the exact search string you were using when searching for this image(s) ?

Here is a screenshot of what I get: [Link](https://www.picflash.org/picture.php?key=34XTZ5&action=show) - as a note, the image is below the 100 mark in my list.

**Comment by Krando** [comment]
> Thank you for your feedback, it is much appreciated!
> 
> In order to follow up - could you provide me with the exact search string you were using when searching for this image(s) ?
> 
> Here is a screenshot of what I get: [Link](https://www.picflash.org/picture.php?key=34XTZ5&action=show) - as a note, the image is below the 100 mark in my list.

It's not about the specific search string. For any search, beyond 100 images, it is not possible to view the images directly. By this, I mean that for the first 100 images, you can hover your mouse over the image and "View" will appear. However, after 100 images, this won't happen but even if you click on the image, nothing will appear.

Search for "dogs" and see if you get to view any image directly after the first 100. After you click on a image, what happens? Does "View" appear?

On my side, here's what it looks like:

Below the 100 mark, "View" appears on an image: https://i.imgur.com/l4iYQ8R.png

However, beyond it, this is what happens if you hover your mouse over the image: https://i.imgur.com/R3CWbaw.png (I hovered it over the image called "Camp dogs and Darwin specials")

If you click on it specifically, this is what appears: https://i.imgur.com/fxrdT3j.png

As you can see, it is not possible to view the image.

**Comment by jrie** [comment]
Ah, now I understand what you have been talking about. I thought the error was different, regarding the searched images, where it is still lightly possible that some caused hickups.

Never the less I added a feature fix here on Github. Could you try this version by downloading the add from here as zip, and using "about:debugging" to load the zip file or better, unpack the add on and load the "manifest.json" of the zip?

Then you can test the new version.

**Comment by jrie** [comment]
Resolved in Version 2.0.2

Image are now clickable and the "View" Link is created.
