### ISSUE TITLE
Not working anymore in Chrome

### ISSUE THREAD

**Issue by fharper** [jrie/googlePanicImage#3]
First, let me say this is such an useful extension, thanks for doing it.

I can't speak for other browsers, but on Chrome 122.0.6261.69, it's not working anymore. I assume it's either a browser update, or a Google Search Image one. Unless it's a code 18, and it's only just me.

**Comment by jrie** [comment]
Hello @fharper and I am glad you like the extension, much appreciated.

I tested in the exact same Chrome version [ v122.0.6261.69 ] - but for me, the extension is working as expected.
For reference, the images above position/index 100 require a additional click, on the image, in order for the view link to appear.

Also, it is required that the extension has permissions to read and make changes on the "current website" or "all websites".
The current website can be any Google domain you are viewing the images on. Like Google.com, Google.de, Google.fr or so forth - or alternatively "allow on all websites".

This options can be found in the "extensions menu" of Chrome, selecting the "GooglePanicImages" options (3 dot menu) and changing "Can read and change website data" to the Google URL you are using or all websites.

That should do the trick! :)

**Comment by fharper** [comment]
So sorry, I should have done more extensive tests before creating the issue. It's working on incognito mode, so I now have something interfering with it. I'm just so used to extensions for Google which stop working because of Google's changes, my bad. Will find what it is, but closing this issue.

Thanks again :)

**Comment by jrie** [comment]
All fine. If the case occurs that another extension is interfering or a browser option/mode or similar, please let me know, so I can provide this information for others in the Readme.

Thx! :+1:

**Comment by fharper** [comment]
If someone stumbles on this issue, I tried everything: no extensions were interfering nor changed flags.

To fix the issue, I switched my Google Search logged account, to another one, and when I switched back to the initial one, the extension started working again. I assume it would do the same if you log out, and log in again. The account switch I made was in the google website, not the Chrome profile.

I really have no idea why it wasn't working anymore, and why doing that made it work again: it was a last tentative to find what was interfering, but I didn't have much hope 😅

**Comment by iiiGerardoiii** [comment]
I think it's not working again, the "view" button doesn't show up.
I've tried it on Firefox and Chrome, on 2 different laptops.

**Comment by fharper** [comment]
The issue happens often for me. I can't find when exactly it stop working.

**Comment by jrie** [comment]
Hello. The Google image search was apparently updated and the addon needs modifications.

**Comment by jrie** [comment]
Hello, a new (complete rewritten) version is out, if you have not checked out, please do so! :)

Closing this issue.

**Comment by fharper** [comment]
The new release fixed the issue on Chrome (I didn't test on other browsers), thanks @jrie 🎉
